apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Value.ratings.namespace}}
spec:
  type: {{ .Value.ingress.serviceType}}
  ports:
  - port: {{ .Value.ratings.port}}
  selector:
    app: {{ .Release.Name }}