apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ .Value.ratings.namespace}}
spec:
  rules:
  - host: {{ .Value.ingress.host}}
    http:
      paths:
      - path: {{ .Value.ingress.path}}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Value.ratings.port}}