ratings:
  namespace: student67-bookinfo-prd
  image: ghcr.io/ppitchanon/bookinfo-ratings
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-prd-ratings-mongodb-secret
ingress:
  host: bookinfo.opsta.net
  path: "/student67/ratings(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-prd-ratings-mongodb:27017/ratings